### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Libidine** [KichangKim/DeepDanbooru#1]
Hi, um, I get a strange error when I run this command in the console:
`python program.py create-project .\test\`
**Log:**
```
Traceback (most recent call last):
  File "program.py", line 5, in <module>
    import deepdanbooru.commands
  File "C:\Users\User\Desktop\DeepDanbooru-master\deepdanbooru\commands\__init__.py", line 1, in <module>
    from .create_project import create_project
  File "C:\Users\User\Desktop\DeepDanbooru-master\deepdanbooru\commands\create_project.py", line 15
    print(f'New project was successfully created. ({project_path})')
                                                                  ^
SyntaxError: invalid syntax
```
I have not changed the original files, and as far as I can tell the problem is not in the command, although I have no experience with Python.

I installed all dependencies using pip (globally)
I'm using **_Python 3.5.2_**
My system: **_Windows 10 1909_**

**Comment by KichangKim** [comment]
Can you try with Python 3.6? 3.5 is not supported.

**Comment by Libidine** [comment]
Well, I reinstalled everything, now there is no more this error, but for some reason tensorflow broke.
```
PS C:\Users\User\Desktop\DeepDanbooru-master> python program.py create-project .\test\
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: the dynamic link library (DLL) initialization program failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "program.py", line 5, in <module>
    import deepdanbooru as dd
  File "C:\Users\User\Desktop\DeepDanbooru-master\deepdanbooru\__init__.py", line 1, in <module>
    import deepdanbooru.commands
  File "C:\Users\User\Desktop\DeepDanbooru-master\deepdanbooru\commands\__init__.py", line 4, in <module>
    from .train_project import train_project
  File "C:\Users\User\Desktop\DeepDanbooru-master\deepdanbooru\commands\train_project.py", line 6, in <module>
    import tensorflow as tf
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>        
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>        
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: the dynamic link library (DLL) initialization program failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
I installed it as follows:

```
PS C:\Users\User\Desktop\DeepDanbooru-master> pip install tensorflow==2.1.0rc1
Collecting tensorflow==2.1.0rc1
...
Successfully installed tensorflow-2.1.0rc1
```
What could have gone wrong?

**Comment by KichangKim** [comment]
Try to re-install tensorflow==2.1.0rc1 with -U option.
```
pip install tensorflow==2.1.0rc1 -U
```
or, check that valid CUDA library is installed and environment variable is configured correctly.
See https://www.tensorflow.org/install/gpu#windows_setup

**Comment by Libidine** [comment]
> Try to re-install tensorflow==2.1.0rc1 with -U option.
> 
> ```
> pip install tensorflow==2.1.0rc1 -U
> ```
> or, check that valid CUDA library is installed and environment variable is configured correctly.
> See https://www.tensorflow.org/install/gpu#windows_setup

None of this helped.

Well, I solved the problem in a different way (https://github.com/tensorflow/tensorflow/issues/23683#issuecomment-510718458), I removed everything related to Python, and installed Anaconda, installed Tensorflow in it, and started using its environment, instead of the old Python 3.6 installed.

**Comment by KichangKim** [comment]
Additional note : TensorFlow 2.1rc or newer, it requires Microsoft Visual C++ Redistributable for Windows user. It can be downloaded from https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads 

From release note of TensorFlow 2.1rc2
> Windows users: Officially-released tensorflow Pip packages are now built with Visual Studio 2019 version 16.4 in order to take advantage of the new /d2ReducedOptimizeHugeFunctions compiler flag. To use these new packages, you must install "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019", available from Microsoft's website here.
This does not change the minimum required version for building TensorFlow from source on Windows, but builds enabling EIGEN_STRONG_INLINE can take over 48 hours to compile without this flag. Refer to configure.py for more information about EIGEN_STRONG_INLINE and /d2ReducedOptimizeHugeFunctions.
If either of the required DLLs, msvcp140.dll (old) or msvcp140_1.dll (new), are missing on your machine, import tensorflow will print a warning message.
