### ISSUE TITLE
ValueError: Unknown layer: Functional

### ISSUE THREAD

**Issue by Superfloh** [KichangKim/DeepDanbooru#26]
When trying to load the v3 or v4 model I get the following error log:

```
2020-11-06 23:01:33.522590: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:/Users/someone/PycharmProjects/deep-gelbooru/download_images.py", line 809, in <module>
    create_image_with_tags(project)
  File "C:/Users/someone/PycharmProjects/deep-gelbooru/download_images.py", line 414, in create_image_with_tags
    project_context, model, tags = dd.project.load_project(project)
  File "C:\Users\someone\PycharmProjects\deep-gelbooru\deepdanbooru\project\project.py", line 38, in load_project
    model = tf.keras.models.load_model(model_path)
  File "C:\Users\someone\Anaconda3\envs\deep-gelbooru\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\Users\someone\Anaconda3\envs\deep-gelbooru\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "C:\Users\someone\Anaconda3\envs\deep-gelbooru\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\someone\Anaconda3\envs\deep-gelbooru\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "C:\Users\someone\Anaconda3\envs\deep-gelbooru\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "C:\Users\someone\Anaconda3\envs\deep-gelbooru\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional
```

Using Windows,

tensorflow-gpu: 2.1.0
Click: 7.1.2
numpy: 1.18.5
requests: 2.24.0
scikit-image: 0.16.2 
six: 1.15.0
python: 3.6.10

Using the v1 model works fine.
Any ideas what the problem could be ?

**Comment by KichangKim** [comment]
Try latest TensorFlow (2.3.1).

**Comment by Superfloh** [comment]
Sadly the conda version of TensorFlow only got updated to 2.1.0 so far, but I will give the pip version a try tomorrow.

**Comment by Superfloh** [comment]
Yeah it's working with TensorFlow 2.3.1, closing the issue.
