### ISSUE TITLE
ValueError: source code string cannot contain null bytes 

### ISSUE THREAD

**Issue by nagaisa** [KichangKim/DeepDanbooru#71]
unable to run deepdanbooru (via [AUTOMATIC1111/stable-diffusion-webui) geting this:
`Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main                                                                                     exitcode = _main(fd, parent_sentinel)                                                                                 File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 125, in _main                                                                                          prepare(preparation_data)                                                                                             File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 236, in prepare                                                                                        _fixup_main_from_path(data['init_main_from_path'])                                                                    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path                                                                          main_content = runpy.run_path(main_path,                                                                              File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 288, in run_path                                                                                                       code, fname = _get_code_from_file(run_name, path_name)                                                                File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 257, in _get_code_from_file                                                                                            code = compile(f.read(), fname, 'exec')                                                                             ValueError: source code string cannot contain null bytes`

**Comment by KichangKim** [comment]
It seems that the error is not part of DeepDanbooru. You should ask to `AUTOMATIC1111/stable-diffusion-webui`.

**Comment by nagaisa** [comment]
> It seems that the error is not part of DeepDanbooru. You should ask to `AUTOMATIC1111/stable-diffusion-webui`.

have tryed but had no reply so far
