### ISSUE TITLE
module 'tensorflow' has no attribute 'lite

### ISSUE THREAD

**Issue by UiharuKazari2008** [KichangKim/DeepDanbooru#81]
```
evaluate ./temp/ --project-path ./model/ --allow-folder --save-json --save-path ./results/ --no-tag-output --allow-gpu
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ykaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts\deepdanbooru.exe\__main__.py", line 4, in <module>
  File "C:\Users\ykaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\deepdanbooru\__init__.py", line 7, in <module>
    import deepdanbooru.commands
  File "C:\Users\ykaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\deepdanbooru\commands\__init__.py", line 1, in <module>
    from .convert_to_tflite import convert_to_tflite_from_from_saved_model
  File "C:\Users\ykaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\deepdanbooru\commands\convert_to_tflite.py", line 8, in <module>
    optimizations: List[tf.lite.Optimize] = [tf.lite.Optimize.DEFAULT],
AttributeError: module 'tensorflow' has no attribute 'lite
```

I keep getting this error no matter what version of tensorflow I have installed

**Comment by UiharuKazari2008** [comment]
I been able to fix this. Apparently there a whole issue with using the Microsoft Store version of Python makes me wonder why its even published if nothing works with it...

That and if your like me and you get that version due to not being able to find the installer, you have to scroll pretty far down the page of the version archives because the top results are version that have no downloads leaving people like me to believe support has been dropped.
